### ISSUE TITLE
dangerous implementation of transferFrom spender allowance validation

### ISSUE THREAD

**Issue by masha256** [ERC-3643/ERC-3643#3]
The implementation of `transferFrom` in the Token.sol contract relies on an arithmetic underflow in order to prevent an unapproved spender to spend a holders tokens:

https://github.com/ERC-3643/ERC-3643/blob/main/contracts/token/Token.sol#L228

Here is an example attempt of a spender who has no previous `approval()` attempting to spend a holders token using `transferFrom`:

```
➜  contracts git:(develop) ✗ cast call 0x0165878A594ca255338adfa4d48449f69242Eb8F "transferFrom(address,address,uint256)" 0xa0Ee7A142d267C1f36714E4a8F75612F20a79720 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 50000 --private-key 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d --rpc-url http://127.0.0.1:8545 --trace
Traces:
  [36869] 0x0165878A594ca255338adfa4d48449f69242Eb8F::transferFrom(0xa0Ee7A142d267C1f36714E4a8F75612F20a79720, 0x70997970C51812dc3A010C7d01b50e0d17dc79C8, 50000 [5e4])
    ├─ [365] 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0::isVerified(0x70997970C51812dc3A010C7d01b50e0d17dc79C8) [staticcall]
    │   └─ ← 0x0000000000000000000000000000000000000000000000000000000000000001
    ├─ [14535] 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9::canTransfer(0xa0Ee7A142d267C1f36714E4a8F75612F20a79720, 0x70997970C51812dc3A010C7d01b50e0d17dc79C8, 50000 [5e4]) [staticcall]
    │   ├─ [6569] 0x5FbDB2315678afecb367f032d93F642f64180aa3::moduleCheck(0xa0Ee7A142d267C1f36714E4a8F75612F20a79720, 0x70997970C51812dc3A010C7d01b50e0d17dc79C8, 50000 [5e4], 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9) [staticcall]
    │   │   ├─ [2308] 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9::getTokenBound() [staticcall]
    │   │   │   └─ ← 0x0000000000000000000000000165878a594ca255338adfa4d48449f69242eb8f
    │   │   ├─ [624] 0x0165878A594ca255338adfa4d48449f69242Eb8F::balanceOf(0xa0Ee7A142d267C1f36714E4a8F75612F20a79720) [staticcall]
    │   │   │   └─ ← 0x00000000000000000000000000000000000000000000000000000000000f4240
    │   │   └─ ← 0x0000000000000000000000000000000000000000000000000000000000000001
    │   └─ ← 0x0000000000000000000000000000000000000000000000000000000000000001
    └─ ← panic: arithmetic underflow or overflow (0x11)
```

`0x0165878A594ca255338adfa4d48449f69242Eb8F`: ERC-3643 token
`0xa0Ee7A142d267C1f36714E4a8F75612F20a79720`: Current holder of the above token
`0x70997970C51812dc3A010C7d01b50e0d17dc79C8`: Attempted attacker 

The private key in the above example is of the attackers address, and is account 2 from a local anvil dev chain.

Highly recommend adding a `_spendAllowance` function like that can be found in the OpenZeppelin ERC20.sol implementation: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol#L151 to avoid any compiler-version relied upon arithmetic handling as well as reverting with a more clear message, such as "insufficient allowance".

**Comment by Joachim-Lebrun** [comment]
that's a valid point, even tho the arithmetic underflow should revert, but a clearer message in case allowance is insufficient is good practice. We will add that to the next version of the contracts

**Comment by Joachim-Lebrun** [comment]
this will be managed on tokeny's repository https://github.com/TokenySolutions/T-REX/issues/216
